apiVersion: batch/v1
kind: Job
metadata:
  name: scan
spec:
  template:
    spec:
      containers:
      - name: client
        image: gcr.io/optical-scan/github.com/milesmcc/mieql:5d44b97
        args:
        - '--threads=4'
        - '--queue=64'
        - '--secret-key=8L3GmlFfsG79V7GoVNaw-5sjs0IbwO5zxlbZ8iBZ'
        - '--master=http://35.196.30.161/api'
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_access_key_id
        resources:
          requests:
            cpu: 3750m
      restartPolicy: OnFailure