apiVersion: batch/v1
kind: Job
metadata:
  name: scan
spec:
  parallelism: 8
  template:
    spec:
      containers:
      - name: master
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:0e2a361ef819390c16773dd5c3867138ab1d393f
        args:
        - master
        - '--database=$(POSTGRES_URL)'
        - '--remove'
        ports:
         - name: http
           containerPort: 3000
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: url
      - name: client
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:0e2a361ef819390c16773dd5c3867138ab1d393f
        args:
        - client
        - '--threads=2'
        - '--queue=32'
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_access_key_id
      restartPolicy: Never