apiVersion: apps/v1
kind: Deployment
metadata:
  name: mieql-scanner
  labels:
    app: mieql
spec:
  selector:
    matchLabels:
      app: mieql
  template:
    metadata:
      labels:
        app: mieql
    spec:
      containers:
      - name: client
        image: gcr.io/optical-scan/github.com/milesmcc/mieql:ea4c5e8
        args:
        - '--threads=4'
        - '--queue=64'
        - '--secret-key=8L3GmlFfsG79V7GoVNaw-5sjs0IbwO5zxlbZ8iBZ'
        - '--master=http://35.196.30.161/api'
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_access_key_id
        resources:
          requests:
            cpu: 3350m