apiVersion: batch/v1
kind: Job
metadata:
  name: scan
spec:
  backoffLimit: 50
  parallelism: 3
  template:
    spec:
      containers:
      - name: master
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:d1c5ad6bbdd41366bb234452c7f28a2ee66d5e21
        args:
        - master
        - '--database=$(POSTGRES_URL)'
        - '--remove'
        ports:
         - name: http
           containerPort: 3000
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: url
        resources:
          requests:
            cpu: 100m
      - name: client
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:d1c5ad6bbdd41366bb234452c7f28a2ee66d5e21
        args:
        - client
        - '--threads=6'
        - '--queue=64'
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_access_key_id
        resources:
          requests:
            cpu: 6900m
      restartPolicy: OnFailure