apiVersion: batch/v1
kind: Job
metadata:
  name: scan
spec:
  template:
    spec:
      containers:
      - name: master
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:506c0c8be596a10a61b2ae2fd8f539b26dd571f7
        args:
        - master
        - '--database=$(POSTGRES_URL)'
        ports:
         - name: http
           containerPort: 3000
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: url
      - name: client
        image: gcr.io/mieql-230000/github.com/milesmcc/mieql:506c0c8be596a10a61b2ae2fd8f539b26dd571f7
        args:
        - client
        - '--threads=2'
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: aws_access_key_id
      restartPolicy: Never