apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  url: "postgres://user:password@ip/database"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  aws_access_key_id: "value"
  aws_secret_access_key: "value"